#config file
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    
    working_directory: ~/repo

    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual enc and install dependencies
      - run:
        name: install dependencies
        command:  |
          python -m vvenv venv
          venv\Scripts\activate.bat
          pip install -r requirements.txt
      # Step 3: run linter and tests
      - run:
          name: run tests
          command:  |
            venv\Scripts\activate.bat
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator